inherit_gem:
  rubocop-github:
    - config/default.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - .vscode
    - node_modules
    - public
    - web
Style/FrozenStringLiteralComment:
  Enabled: true
Style/BlockComments:
  Enabled: true
