inherit_gem:
  rubocop-github:
    - config/default.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - .vscode
    - agents
    - node_modules
    - public
    - venv
    - web
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
