inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
AllCops:
  Exclude:
    - .vscode
    - agents
    - node_modules
    - public
    - venv
    - web
Rails:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
