matrix:
  include:
    - language: ruby
      rvm:
        - ruby-2.6
      services:
        - postgresql
      before_script:
        - psql -c 'create database backdoor_test;' -U postgres
        - HANAMI_ENV=test bundle exec hanami db prepare
      script:
        - bundle exec rspec
        - bundle exec rubocop
