version: '3.5'

networks:
  quatrolabs-watchman-network:
    driver: bridge

services:
  watchman-postgres:
    image: 'postgres:11.3'
    container_name: watchman-postgres
    hostname: watchman-postgres
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: watchman
      POSTGRES_PASSWORD: 8GWbz2JF4FMe1Q8X
      POSTGRES_DB: backdoor_production
      POSTGRES_HOST_AUTH_METHOD: "trust"
      listen_addresses: "*"
    networks:
      - quatrolabs-watchman-network

  watchman:
    build:
      context: .
    container_name: watchman
    image: watchman
    depends_on:
      - watchman-postgres
    links:
      - watchman-postgres
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      WATCHMAN_WEB_SESSIONS_SECRET: xRaQLWtL2JUcr8hjgglQOVJ6hRZhIZ6MitXhORpH4ToN7E5OSsVWugEkLdCLikfJ
      WATCHMAN_API_SESSIONS_SECRET: xRaQLWtL2JUcr8hjgglQOVJ6hRZhIZ6MitXhORpH4ToN7E5OSsVWugEkLdCLikfJ
      WATCHMAN_DATABASE_URL: postgresql://watchman:8GWbz2JF4FMe1Q8X@watchman-postgres/backdoor_production
    networks:
      - quatrolabs-watchman-network
